const a = 1
const b = 2
const c = 3
const d = 4
const e = 5
console.log (a + b);
console.log (a - b);
console.log (d / 2);
console.log (c * b);
console.log (c > a);
console.log (a < e);
console.log (a+b === c);
console.log (b !== d);